### ISSUE TITLE
Add Contribution guide to the project

### ISSUE THREAD

**Issue by pk400** [Midnight-Cafe/lacus#17]
# Description

To make it easier for new contributors to get started on the project it would be nice to have a simple guide explaining how to pull the repo, push changes, create issues, create pull requests, etc.

# Acceptance Criteria

- A contribution guide file has been added to the codebase

**Comment by ghost** [comment]
I can take this issue

**Comment by pk400** [comment]
Sweet! Thanks @riboney !
