### ISSUE TITLE
Timezone Converter

### ISSUE THREAD

**Issue by jyorien** [Midnight-Cafe/lacus#23]
# Description

Timezone converter for the bot so that we can see what time are Weekly Syncs in our own timezones
# Acceptance Criteria

- Bot can send a list of timezones with their equivalent times given an input e.g 
1/9/21 1900 PDT ->
GMT +8: 2/9/21 1000
(this template can be changed)

**Comment by pk400** [comment]
I think this would be great, for me personally to help organize the events better and for the rest of the community! Can we make it support having many events (not just Weekly Syncs) with each their own scheduled date and time?

Example:
```
breeze.astraea.systems: !events add "Weekly Sync" <timestamp> <timezone>
Lacus: "Weekly Sync" scheduled for <timestamp> <timezone>
```
Ideally *<timestamp>* would be an ISO 8601 timestamp and *<timezone>* would be something like **America/Vancouver**. It should also automatically remove itself after the event has passed.

Not sure if there are any better ways to make this a command, this is just the first thing that came to my head.

**Comment by jyorien** [comment]
> I think this would be great, for me personally to help organize the events better and for the rest of the community!

> It should also automatically remove itself after the event has passed.

Saving an event and auto deleting it sounds great feature, we could even make reminders out of the saved events, however would that be considered a separate issue? 
For this issue, would it be enough just to get the timezone conversion working? e.g. like this fff6c20

**Comment by pk400** [comment]
Yup that sounds good let's do that in a separate ticket. Your PR looks good so far, its a draft atm so let me know when its ready for a review and I can take a look again.
