### ISSUE TITLE
[Bug] AttributeError: 'NoneType' object has no attribute 'fetch_message'

### ISSUE THREAD

**Issue by jyorien** [Midnight-Cafe/lacus#29]
# Steps to Reproduce
1. Start python app.py
2. Error appears after a few seconds

> Ignoring exception in on_ready
Traceback (most recent call last):
  File "lacus/env/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "lacus/lacus/cogs/general.py", line 15, in on_ready
    await self.set_welcome_message()
  File "lacus/lacus/cogs/general.py", line 23, in set_welcome_message
    message = await channel.fetch_message(880000637998338079)
AttributeError: 'NoneType' object has no attribute 'fetch_message'

**Comment by pk400** [comment]
Ah, I guess we'll need to set the welcome channel id in the `LacusConfig` also. I was a little lazy and hard-coded it in, but now its affecting everyone trying to test the bot out in their test servers. Woops.

**Comment by pk400** [comment]
I can take this one.
